src/carts/urls.py
from django.urls import path

from .views import (
    cart_home, 
    cart_update, 
    checkout_home
    )

app_name = "cart" # django 2 feature for namespace to work in main url file

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update')
] 

src/ecommerce/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import login_page, register_page, guest_register_view
from .views import home_page, about_page, contact_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register')
] 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/products/urls.py
from django.urls import path

from .views import(
    ProductListView,
    ProductDetailSlugView,
) 

app_name = "products" # django 2 feature for namespace to work in main url file

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail')
] 

src/ecommerce/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class ContactForm(forms.Form):
    fullname  = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 
                'placeholder': 'Your full name'
            }
        )
    )
    email     = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control', 
                'placeholder': 'Your email'
            }
        )
    )
    content   = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control', 
                'placeholder': 'Your content'
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not "gmail.com" in email:
            raise forms.ValidationError("Email has to be gmail.com")
        return email   

src/ecommerce/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import ContactForm


def home_page(request):
    #print(request.session.get("first_name", "Unknown"))
    # request.session['first_name']
    context = {
        'title' : 'Hello World',
        'content' : 'Welcome to the homepage.'
    }
    if request.user.is_authenticated:
        context["premium_content"] = "YEEAAAHHHH"
    return render(request, 'pages/home.html', context)

def about_page(request):
    context = {
        'title' : 'About Page',
        'content' : 'Welcome to the about page.'
    }
    return render(request, 'pages/about.html', context)

def contact_page(request):
    contact_form = ContactForm(request.POST or None)
    context = {
        'title' : 'Contact Page',
        'content' : 'Welcome to the contact page.',
        'form' : contact_form
    }
    if contact_form.is_valid():
        print(contact_form.cleaned_data)
    # if request.method == "POST":
    #     #print(request.POST)
    #     print(request.POST.get('fullname'))
    #     print(request.POST.get('email'))
    #     print(request.POST.get('content'))
    return render(request, 'pages/contact.html', context)

src/ecommerce/templates/partials/footer.html
<footer class="text-muted pt-5" style="margin-top: 5.5625em;">
    <hr/>
    <div class="container text-center">
        <p>&copy; FarangRoll {% now "Y" %}</p>
    </div>
</footer>

{% include 'base/js.html' %}
</body>

</html>

src/ecommerce/templates/partials/header.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>FarangRoll</title>
    <!-- Custom External CSS -->
    {% include 'base/css.html' %}
    <!-- Custom Inline CSS -->
    {% block base_head %}{% endblock %}

</head>

<body>

    <header>
        <!--  -->
        {% url 'home' as home_url %}
        <!--  -->
        {% url 'contact' as contact_url %}
        <!--  -->
        {% url 'products:list' as product_list_url %}
        <!--  -->
        {% url 'about' as about_url %}
        <!--  -->
        {% url 'login' as login_url %}
        <!--  -->
        {% url 'logout' as logout_url %}
        <!--  -->
        {% url 'register' as register_url %}
        <!--  -->
        {% url 'cart:home' as cart_url %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{{ home_url }}">
                    <img src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt=""> {% if brand_name %} {{ brand_name }} {% else %}
                    <h1>JBM eCommerce</h1>
                    {% endif %}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto pl-5">
                        <!-- <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                        <a class="nav-link" href="{{ home_url }}">Home</a>
                    </li> -->
                        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                            <a class="nav-link" href="{{ contact_url }}">Contact</a>
                        </li>
                        <li class="nav-item {% if request.path == about_url %}active{% endif %}">
                            <a class="nav-link" href="{{ about_url }}">About</a>
                        </li>
                        <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                            <a class="nav-link" href="{{ product_list_url }}">Products</a>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                            <a class="nav-link" href="{{ logout_url }}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                            <a class="nav-link" href="{{ register_url }}">Register</a>
                        </li>
                        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                            <a class="nav-link" href="{{ login_url }}">Login</a>
                        </li>
                        {% endif %}
                        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                            <a class="nav-link" href="{{ cart_url }}">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i><sup>{{ request.session.cart_items }}</sup>
                            </a>
                        </li>
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown
                        </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li> -->
                    </ul>
                    {% include 'search/snippets/search-form.html' %}
                </div>
            </div>
        </nav>
    </header>